### ISSUE TITLE
[ENV_READER] 💥 Unable to load data 💥

### ISSUE THREAD

**Issue by Prashant4900** [Nialixus/env_reader#1]
**Describe the bug**
After updating into new version (2.0.3) its start showing the error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Create .env file in root directory
  ```bash
  Env1=**************
  Env2=**************
  ```
2. Run the command to generate models
  ```bash
  dart run env_reader --input=".env" --output="assets/env/" --key=="Password@123" --model="lib/gen/env_model.dart" --null-safety
  ```
3. Add generated assets file in pubspec.yaml
```bash
assets:
    - assets/env/
```
4. Update main.dart
```bash
import 'package:flutter/services.dart' show rootBundle;
... rest packages ...
import 'package:env_reader/env_reader.dart';

Future<void> main() async {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  final production = EnvReader();
  await production.load(
    EnvStringLoader(await rootBundle.loadString('assets/env/.env')),
    'Password@123',
  );
  FlutterNativeSplash.remove();
  runApp(const MyApp());
}
```

5. Run the app and saw the error in console:
```bash
[log] 
      
      [ENV_READER] 💥 Unable to load data 💥
      SecretBoxAuthenticationError: SecretBox has wrong message authentication code (MAC)
```

**Screenshots**
![image](https://github.com/Nialixus/env_reader/assets/62440911/20e7a2fc-60f9-4246-b203-3980d01d54af)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version M1 Air 2020

**Smartphone (please complete the following information):**
 - Device: Simulator

**Comment by Nialixus** [comment]
Hi there, i see that the secret key that you run in step number 2 was _**Password@123**_, 
but when you load it you are using _**Nigam.123**_. This doesn't match.

The solution for this is either 
> run the command with _**Nigam.123**_ as the secret key

or

> load the env with _**Password@123**_ as its secret key

**Comment by Prashant4900** [comment]
No, This is a Dummy password which i forgot to change. 

The problem is there if I still use same key.

**Comment by Nialixus** [comment]
I think it's related to breaking change due to the encryption i use were different between version 1 and 2, or maybe something wrong with the encryption package

Could you try this again

> **Step 1**
> ``` bash
> dart pub global activate env_reader
> ```

> **Step 2**
> ```bash
> env_reader --input=".env" --output="assets/env/" --key="Nigam.123"
> ```

> **Step 3**
> Don't forget hot restart

If the issue still persist, please let me know
I might need to change the encryption package again

**Comment by Prashant4900** [comment]
This command is not creating the Envmodel class but yes Issue is still the same

```bash
env_reader --input=".env" --output="assets/env/" --key="Nigam.123"
```

**Comment by Nialixus** [comment]
Hi, I have successfully reproduced the issue you encountered.
The problem was related to [this GitHub issue](https://github.com/dint-dev/cryptography/issues/147). 
I resolved it by downgrading the cryptography package and testing it, and it appears to work correctly.

you can upgrade env_reader to ^2.1.0 and just to be safe, do this again.

```bash
env_reader --input=".env" --output="assets/env/" --key="Nigam.123"
```
